#!/usr/bin/env python3
"""
Initialize default API keys for the Analysis Module.

This script creates default API keys for development and testing purposes.
"""

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List

import yaml

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

# Import with fallback for missing modules
try:
    from src.llama_mapper.analysis.infrastructure.auth import (
        APIKeyManager,
        APIKeyRequest,
    )

    LLAMA_MAPPER_AVAILABLE = True
except ImportError as e:
    print(f"Warning: Cannot import llama_mapper modules: {e}")
    print("Running in mock mode - install the package for full functionality")
    LLAMA_MAPPER_AVAILABLE = False

    # Mock classes for development/testing
    class _MockAPIKeyManager:
        def __init__(self, *args, **kwargs):
            pass

        def create_api_key(self, *args, **kwargs):
            return None

    class _MockAPIKeyRequest:
        def __init__(self, *args, **kwargs):
            pass

    # Assign mocks to the expected names
    APIKeyManager = _MockAPIKeyManager
    APIKeyRequest = _MockAPIKeyRequest


# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def load_config(config_path: str) -> Dict[str, Any]:
    """
    Load API key configuration from YAML file.

    Args:
        config_path: Path to configuration file

    Returns:
        Configuration dictionary
    """
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f)
        return config
    except (FileNotFoundError, PermissionError, yaml.YAMLError) as e:
        logger.error("Failed to load configuration from %s: %s", config_path, e)
        sys.exit(1)


def create_default_keys(
    api_key_manager: Any, config: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
     Create default API keys from configuration.

     Args:
         api_key_manager: API key manager instance
         config: Configuration dictionary

    Returns:
         List of created key information
    """
    created_keys = []
    default_keys = config.get("default_keys", [])

    for key_config in default_keys:
        try:
            # Create API key request
            request = APIKeyRequest(
                tenant_id=key_config["tenant_id"],
                name=key_config["name"],
                description=key_config.get("description", ""),
                scopes=key_config.get("scopes", ["analyze"]),
                expires_in_days=key_config.get("expires_in_days"),
                rate_limit=key_config.get("rate_limit"),
            )

            # Create the API key
            response = api_key_manager.create_api_key(request)
            if response:
                created_keys.append(
                    {
                        "key_id": response.key_id,
                        "api_key": response.api_key,
                        "tenant_id": response.tenant_id,
                        "name": response.name,
                        "description": response.description,
                        "scopes": response.scopes,
                        "expires_at": response.expires_at,
                        "rate_limit": response.rate_limit,
                    }
                )
                logger.info("Created API key: %s (%s)", response.name, response.key_id)
            else:
                logger.error("Failed to create API key: %s", key_config["name"])

        except (ValueError, RuntimeError, ConnectionError) as e:
            logger.error(
                "Error creating API key %s: %s", key_config.get("name", "unknown"), e
            )

    return created_keys


def save_keys_to_file(keys: List[Dict[str, Any]], output_file: str):
    """
    Save created API keys to a file.

    Args:
        keys: List of created key information
        output_file: Output file path
    """
    try:
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(keys, f, indent=2)

        logger.info("Saved %s API keys to %s", len(keys), output_file)

    except (FileNotFoundError, PermissionError, OSError) as e:
        logger.error("Failed to save keys to %s: %s", output_file, e)


def create_env_file(keys: List[Dict[str, Any]], env_file: str):
    """
    Create environment file with API key variables.

    Args:
        keys: List of created key information
        env_file: Environment file path
    """
    try:
        env_path = Path(env_file)
        env_path.parent.mkdir(parents=True, exist_ok=True)

        with open(env_path, "w", encoding="utf-8") as f:
            f.write("# API Keys for Analysis Module\n")
            f.write("# Generated by init_api_keys.py\n\n")

            for key in keys:
                # Create environment variable name
                env_name = f"API_KEY_{key['key_id'].upper().replace('-', '_')}"
                f.write(f"{env_name}={key['api_key']}\n")
                f.write(f"# {key['name']} - {key['description']}\n")
                f.write(
                    f"# Tenant: {key['tenant_id']}, Scopes: {', '.join(key['scopes'])}\n\n"
                )

        logger.info("Created environment file: %s", env_file)

    except (FileNotFoundError, PermissionError, OSError) as e:
        logger.error("Failed to create environment file %s: %s", env_file, e)


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description="Initialize default API keys for Analysis Module"
    )
    parser.add_argument(
        "--config",
        default="config/api_keys.yaml",
        help="Path to API key configuration file",
    )
    parser.add_argument(
        "--output", default="api_keys.json", help="Output file for created API keys"
    )
    parser.add_argument(
        "--env-file",
        default=".env.api_keys",
        help="Environment file for API key variables",
    )
    parser.add_argument("--redis-url", help="Redis URL for key storage (optional)")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be created without actually creating keys",
    )

    args = parser.parse_args()

    try:
        # Load configuration
        logger.info("Loading configuration from %s", args.config)
        config = load_config(args.config)

        # Create API key manager
        api_key_manager = APIKeyManager()

        if args.dry_run:
            logger.info("DRY RUN MODE - No keys will be created")
            default_keys = config.get("default_keys", [])
            for key_config in default_keys:
                logger.info(
                    "Would create key: %s for tenant %s",
                    key_config["name"],
                    key_config["tenant_id"],
                )
            return

        # Create default keys
        logger.info("Creating default API keys...")
        created_keys = create_default_keys(api_key_manager, config)

        if not created_keys:
            logger.warning("No API keys were created")
            sys.exit(1)

        # Save keys to file
        save_keys_to_file(created_keys, args.output)

        # Create environment file
        create_env_file(created_keys, args.env_file)

        # Print summary
        print(f"\n{'='*60}")
        print("API KEY INITIALIZATION COMPLETE")
        print(f"{'='*60}")
        print(f"Created {len(created_keys)} API keys:")
        print()

        for key in created_keys:
            print(f"Key ID: {key['key_id']}")
            print(f"Name: {key['name']}")
            print(f"Tenant: {key['tenant_id']}")
            print(f"Scopes: {', '.join(key['scopes'])}")
            print(f"API Key: {key['api_key']}")
            print(f"Expires: {key['expires_at'] or 'Never'}")
            print(f"Rate Limit: {key['rate_limit'] or 'Default'} requests/minute")
            print("-" * 40)

        print(f"\nKeys saved to: {args.output}")
        print(f"Environment file: {args.env_file}")
        print("\n⚠️  IMPORTANT: Keep these API keys secure!")
        print("   - Store them in a secure location")
        print("   - Don't commit them to version control")
        print("   - Rotate them regularly in production")

    except (ValueError, RuntimeError, ConnectionError) as e:
        logger.error("Error initializing API keys: %s", e)
        sys.exit(1)


if __name__ == "__main__":
    main()
